/* 
 * Aspose.PDF Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Aspose.Pdf.Cloud.Sdk.Client.SwaggerDateConverter;

namespace Aspose.Pdf.Cloud.Sdk.Model
{
    /// <summary>
    /// Specifies style information applied to text.
    /// </summary>
    /// <value>Specifies style information applied to text.</value>
    [Flags]
    public enum FontStyles
    {
        /// <summary>
        /// Regular text
        /// </summary>
        Regular = 0,
        /// <summary>
        /// Bold text
        /// </summary>
        Bold = 1,
        /// <summary>
        /// Italic text
        /// </summary>
        Italic = 2

    }
}
