/* 
 * Aspose.PDF Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Aspose.Pdf.Cloud.Sdk.Client.SwaggerDateConverter;

namespace Aspose.Pdf.Cloud.Sdk.Model
{
    /// <summary>
    /// Represents list of link action types.
    /// </summary>
    /// <value>Represents list of link action types.</value>
    public enum LinkActionType
    {
        /// <summary>
        /// Represents a go-to action that changes the view to a specified destination (page, location, and magnification factor).
        /// </summary>
        GoToAction,
        /// <summary>
        /// Represents a URI action causes a URI to be resolved.
        /// </summary>
        GoToURIAction,
        /// <summary>
        /// Represents javascript action.
        /// </summary>
        JavascriptAction,
        /// <summary>
        /// Represents a launch action that launches an application or opens or prints a document.
        /// </summary>
        LaunchAction,
        /// <summary>
        /// Represents named actions that PDF viewer applications are expected to support.
        /// </summary>
        NamedAction,
        /// <summary>
        /// Represents submit-form action.
        /// </summary>
        SubmitFormAction
    }
}
