/* 
 * Aspose.Pdf for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Aspose.Pdf.Cloud.Sdk.Client.SwaggerDateConverter;

namespace Aspose.Pdf.Cloud.Sdk.Model
{
    /// <summary>
    /// Enumerates the annotation’s highlighting mode, the visual effect to be used when the mouse button is pressed or held down inside its active area.
    /// </summary>
    /// <value>Enumerates the annotation’s highlighting mode, the visual effect to be used when the mouse button is pressed or held down inside its active area.</value>
    public enum LinkHighlightingMode
    {
        /// <summary>
        /// No highlighting.
        /// </summary>
        None,
        /// <summary>
        /// Invert the contents of the annotation rectangle.
        /// </summary>
        Invert,
        /// <summary>
        /// Invert the annotation’s border.
        /// </summary>
        Outline,
        /// <summary>
        /// Display the annotation’s down appearance, if any. If no down appearance is defined, offset the contents of the annotation rectangle to appear as if it were being pushed below the surface of the page.
        /// </summary>
        Push,
        /// <summary>
        /// Same as Push (which is preferred).
        /// </summary>
        Toggle
    }

}
