/* 
 * Aspose.Pdf for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Aspose.Pdf.Cloud.Sdk.Client.SwaggerDateConverter;

namespace Aspose.Pdf.Cloud.Sdk.Model
{
    /// <summary>
    /// Enumeration of possible rotation values.
    /// </summary>
    /// <value>Enumeration of possible rotation values.</value>
    public enum Rotation
    {
        /// <summary>
        /// Non-rotated.
        /// </summary>
        None,
        /// <summary>
        /// Rotated on 90 degrees clockwise.
        /// </summary>
        on90,
        /// <summary>
        /// Rotated on 180 degrees.
        /// </summary>
        on180,
        /// <summary>
        /// Rotated on 270 degrees clockwise.
        /// </summary>
        on270,

    }

}
