/* 
 * Aspose.Pdf for Cloud API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Aspose.Pdf.Cloud.Sdk.Client.SwaggerDateConverter;

namespace Aspose.Pdf.Cloud.Sdk.Model
{
    /// <summary>
    /// 
    /// </summary>
    /// <value></value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum WrapMode
    {
        
        /// <summary>
        /// Enum NoWrap for "NoWrap"
        /// </summary>
        [EnumMember(Value = "NoWrap")]
        NoWrap,
        
        /// <summary>
        /// Enum ByWords for "ByWords"
        /// </summary>
        [EnumMember(Value = "ByWords")]
        ByWords,
        
        /// <summary>
        /// Enum DiscretionaryHyphenation for "DiscretionaryHyphenation"
        /// </summary>
        [EnumMember(Value = "DiscretionaryHyphenation")]
        DiscretionaryHyphenation
    }

}
